server/api/books.js, server/api/index.js, server/api/users.js
=> adding Get for all books

server/db/models/products.js
=> updated product table with imageUrl column

client/components/singleBook.js, server/api/books.js
=> Single book route and react component

client/components/index.js, client/components/navbar.js, client/components/productList.js, client/routes.js, client/store/products.js, server/index.js
=> Productlist -add all books link in the Navbar

server/api/books.js
=> backend product routes added

server/api/users.js
=> Create backend routes for Users and Reviews #41

client/components/navbar.js, client/components/productList.js, client/components/selectCatagory.js, client/store/products.js
=> Select cat

script/deploy, script/seed.js
=> Updated seed file

.travis.yml, client/routes.js, package.json
=> travis: activate deployment

client/components/productCard.js, client/components/singleBook.js, client/routes.js, client/store/products.js
=> Single book view and front end routes added

client/components/navbar.js, client/store/products.js
=> merge bug fix

script/seed.js
=> updating seed

client/components/navbar.js, client/components/selectCatagory.js
=> allbooksworking

client/components/addProduct.js, client/components/index.js, client/components/navbar.js, client/components/productForm.js, client/components/productList.js, client/components/user-home.js, client/routes.js, client/store/products.js, package.json, script/seed.js, server/api/books.js
=> Admin form component

script/seed.js
=> fixed first image link

client/store/products.js
=> fixed missing bracket in store file

client/routes.js
=> fixed tab title

client/app.js, client/components/addToCartButton.js, client/components/productCard.js, client/components/singleBook.js, client/components/viewCart.js, client/routes.js, client/store/cart.js, client/store/index.js, client/store/products.js, server/api/cart.js, server/db/models/user.spec.js, server/index.js
=> Cart button

client/components/productCard.js, client/components/quantity.js
=> add quantity

client/components/reviews.js, client/components/singleBook.js, client/store/index.js, client/store/review.js, package-lock.json, package.json, script/seed.js, server/api/index.js, server/api/reviews.js, server/api/users.js
=> undo revert

client/components/navbar.js, client/components/viewCart.js
=> fixed history button to not render for non logged in users

client/components/navbar.js, client/components/productCard.js, client/components/quantity.js, client/components/viewCart.js, client/store/cart.js, package-lock.json, server/api/cart.js, server/auth/index.js, server/index.js
=> Fix quantity

client/components/quantity.js, client/components/viewCart.js, client/store/cart.js, package-lock.json, server/api/cart.js, server/api/orders.js, server/db/models/productOrder.js
=> fixquantity

client/components/navbar.spec.js, client/components/productCard.spec.js, client/components/quatity.spec.js, client/components/review.spec.js, client/store/cart.spec.js, client/store/products.spec.js
=> Redux test
